### ISSUE TITLE
API- PUT Report

### ISSUE THREAD

**Issue by Zpcolburn** [Zpcolburn/BECapstoneIronAssist#18]
### **Description**
Implement the [Action] route for the [Entity] entity.
- **Entity**: Report
- **Action**: Edit an existing Report

---
### **Task Breakdown**
- [x] Include endpoint in its API file within the APIs folder
- [x] Define the route path.
- [x] Handle request validation and data persistence.
- [x] Implement error handling and appropriate status codes.
- [ ] Test on Swagger

---
### **Request**
- **HTTP Method**: PUT
- **Path**: `/api/report/{id}`
- **Body**:
![image](https://github.com/user-attachments/assets/fbd90105-2e12-472e-923b-1f2d8063bc7b)

```
 ```
### **Response**
- **Status Code**: 200
- **Body**:
![image](https://github.com/user-attachments/assets/c6e92572-8d5d-4cd8-8717-9eced81cacec)

```
 ```
